"""Domain query history — DNS sniffing, hourly rollups, leaderboards, purge.

----------------------------------------------------------------------
SCOPE LIMITATION (stated in the UI and honoured in code):
DNS sniffing shows WHICH DOMAINS were queried by each device. It does NOT
show search terms typed into a search engine, nor the specific pages or
content viewed — that data travels inside encrypted HTTPS and is explicitly
out of scope for this tool. We only ever show what was observed at the DNS
layer; nothing is inferred or fabricated.
----------------------------------------------------------------------

The DnsQueryLog table is rolled up per device+domain+HOUR bucket with an
incrementing counter (one row per bucket, not one row per query) to avoid
row explosion. The sniffer buffers counts in memory and flushes every few
seconds in bulk.
"""
from __future__ import annotations

import logging
import random
import threading
import time
from datetime import timedelta

import config
from netshield.extensions import db
from netshield.models.models import BandwidthSample, Device, DnsQueryLog, utcnow
from netshield.services import dns_categories

logger = logging.getLogger("netshield.history")

FLUSH_INTERVAL = 10          # seconds between bulk DB flushes
SNIFF_FILTER = "udp port 53"

# ---------------------------------------------------------------------------
# Noise filtering — these are NEVER "search history":
#  * reverse-DNS (PTR) lookups (.in-addr.arpa / .ip6.arpa) — generated by
#    the app's own hostname resolver and by devices doing rDNS,
#  * connectivity checks / telemetry / infrastructure domains.
# Filtered at capture time (both the passive sniffer and the ARP relay),
# and existing noise rows are purged once on startup.
# ---------------------------------------------------------------------------
NOISE_SUFFIXES = (".in-addr.arpa", ".ip6.arpa")
NOISE_DOMAINS = {
    "dns.google", "cloudflare-dns.com",
    "connectivity-check.one", "connectivity-check.ubuntu.com",
    "www.msftconnecttest.com", "msftncsi.com", "captive.apple.com",
    "generate_204", "clients3.google.com", "cdn.socket.io",
    "events.data.microsoft.com", "v10.events.data.microsoft.com",
    "watson.telemetry.microsoft.com", "nexusrules.officeapps.live.com",
    "example.com", "example.org",
}


def is_noise_domain(domain: str) -> bool:
    """True when a queried name is infrastructure noise, not browsing."""
    d = (domain or "").strip().lower().rstrip(".")
    if not d:
        return True
    if d.endswith(NOISE_SUFFIXES):
        return True
    for entry in NOISE_DOMAINS:
        if "." in entry:
            if d == entry or d.endswith("." + entry):
                return True
        else:
            if dns_categories.base_domain(d) == entry:
                return True
    return False

# ---------------------------------------------------------------------------
# DNS capture (requires packet capability)
# ---------------------------------------------------------------------------
_pending: dict[tuple[str | None, str, int], int] = {}
_pending_lock = threading.Lock()
_ip_to_mac_cache: dict[str, str] = {}
_ip_cache_ts = 0.0
_own_ips: set[str] = set()
_own_ips_ts = 0.0


def _refresh_own_ips() -> None:
    """IPs of THIS machine — its own DNS traffic must never appear in
    history (the host is infrastructure, not a monitored device)."""
    global _own_ips_ts, _own_ips
    if time.time() - _own_ips_ts < 60:
        return
    _own_ips_ts = time.time()
    try:
        from netshield.services.network_scanner import host_ips
        _own_ips = host_ips()
    except Exception:
        _own_ips = {config.detect_host_ip()}

# live capture statistics (shown on the Traffic page so capture health is
# visible instead of silently failing)
_stats_lock = threading.Lock()
_stats = {"running": False, "queries_seen": 0, "flushes": 0,
          "rows_logged": 0, "last_error": None, "started_at": None}

# When True, DNS capture happens inside the traffic-control ARP relay
# (monitor sessions spoof EVERY device and log their queries here), so the
# passive sniffer stands down to avoid double-counting the same query.
_relay_capture = False


def set_relay_capture(enabled: bool) -> None:
    """Called when full DNS capture (ARP-spoof all devices) is toggled."""
    global _relay_capture
    _relay_capture = bool(enabled)


def relay_capture_active() -> bool:
    return _relay_capture


def _refresh_ip_cache() -> None:
    """Map current_ip -> mac from the registry + OS ARP table (cheap).

    All MACs are normalized so lowercase Scapy/ARP-table formats match the
    uppercase registry keys.
    """
    global _ip_cache_ts, _ip_to_mac_cache
    if time.time() - _ip_cache_ts < 15:
        return
    _ip_cache_ts = time.time()
    mapping: dict[str, str] = {}
    for dev in Device.query.all():
        if dev.current_ip:
            mapping[dev.current_ip] = dev.mac
    try:
        from netshield.services import mac_intel
        from netshield.services.network_scanner import read_arp_table
        for ip, mac in read_arp_table().items():
            norm = mac_intel.normalize_mac(mac)
            if norm:
                mapping.setdefault(ip, norm)
    except Exception:
        pass
    _ip_to_mac_cache = mapping


def record_query(device_mac: str | None, domain: str, ts) -> None:
    """Buffer one observed query into the hour bucket."""
    if not domain:
        return
    if is_noise_domain(domain):
        return  # reverse-DNS lookups / connectivity checks are not history
    from netshield.services import mac_intel
    mac = mac_intel.normalize_mac(device_mac) if device_mac else None
    bucket = ts.replace(minute=0, second=0, microsecond=0)
    key = (mac, domain, int(bucket.timestamp()))
    with _pending_lock:
        _pending[key] = _pending.get(key, 0) + 1
    with _stats_lock:
        _stats["queries_seen"] += 1


def _flush() -> None:
    """Write buffered counts into the hourly-bucketed table.

    FK-safe: a query is only attributed to a MAC that exists in the device
    registry; everything else is logged with device_mac=NULL so the domain
    still appears in network-wide history. On any failure the batch is
    requeued instead of dropped.
    """
    with _pending_lock:
        batch = dict(_pending)
        _pending.clear()
    if not batch:
        return
    valid_macs = {d.mac for d in Device.query.all()}
    try:
        for (device_mac, domain, bucket_ts), count in batch.items():
            mac = device_mac if device_mac in valid_macs else None
            bucket = utcnow().fromtimestamp(bucket_ts)
            row = (DnsQueryLog.query.filter_by(device_mac=mac, domain=domain,
                                               timestamp=bucket).first())
            if row is None:
                db.session.add(DnsQueryLog(device_mac=mac, domain=domain,
                                           timestamp=bucket, count=count))
            else:
                row.count += count
        db.session.commit()
        with _stats_lock:
            _stats["flushes"] += 1
            _stats["rows_logged"] += len(batch)
            _stats["last_error"] = None
    except Exception as exc:
        db.session.rollback()
        # requeue so nothing is lost
        with _pending_lock:
            for key, n in batch.items():
                _pending[key] = _pending.get(key, 0) + n
        with _stats_lock:
            _stats["last_error"] = str(exc)
        logger.warning("query-log flush failed (%s) — batch requeued", exc)


def _sniff_loop(app=None) -> None:
    """Passive DNS sniffer. PACKET-LEVEL NOTE: this only READS UDP/53
    packets in promiscuous mode; it never injects or modifies anything.

    ``app`` is used to give the IP->MAC cache refresh an application
    context — the sniffer thread itself has none, and querying the device
    registry without one used to fail silently on every packet (domains
    were logged with no device attached).
    """
    from scapy.all import sniff

    def _handle(pkt):
        try:
            if _relay_capture:
                # the ARP relay logs DNS for every spoofed device; the
                # passive sniffer would double-count the same packets
                return
            if not pkt.haslayer("DNS") or pkt.getlayer("DNS").qr:
                return  # responses only / not a query
            qd = pkt.getlayer("DNS").qd
            if qd is None or not qd.qname:
                return
            qname = qd.qname.rstrip(b".").decode("ascii", errors="ignore")
            if not qname:
                return
            src = pkt.getlayer("IP").src if pkt.haslayer("IP") else None
            try:
                if app is not None:
                    with app.app_context():
                        _refresh_ip_cache()
                        _refresh_own_ips()
                else:
                    _refresh_ip_cache()
                    _refresh_own_ips()
            except Exception:
                pass  # cache refresh must never stop the sniffer
            if src and src in _own_ips:
                return  # the admin PC's own traffic is never recorded
            mac = _ip_to_mac_cache.get(src) if src else None
            record_query(mac, qname.lower(), utcnow())
        except Exception:
            pass  # one bad packet must never stop the sniffer

    while True:
        with _stats_lock:
            _stats["running"] = True
            _stats["last_error"] = None
        try:
            sniff(store=False, prn=_handle, filter=SNIFF_FILTER)
        except Exception as exc:
            # e.g. "Operation not permitted" (no admin/Npcap) or a bad
            # interface: back off and retry so a temporary permission
            # change gets picked up without hammering the log
            with _stats_lock:
                _stats["running"] = False
                _stats["last_error"] = str(exc)
            logger.warning("DNS sniffer stopped (%s) — retrying in 30s", exc)
            time.sleep(30)


def dns_capture_status() -> dict:
    """Live capture health + DB totals (Traffic page status box)."""
    with _stats_lock:
        stats = dict(_stats)
    try:
        rows = db.session.query(db.func.count(DnsQueryLog.id)).scalar() or 0
        domains = (db.session.query(db.func.count(db.func.distinct(
            DnsQueryLog.domain))).scalar() or 0)
    except Exception:
        rows = domains = 0
    stats["rows_in_db"] = rows
    stats["domains_in_db"] = domains
    stats["mode"] = "full-relay" if _relay_capture else "passive"
    return stats


def start_dns_sniffer(app=None) -> bool:
    """Start the sniffer thread; returns False when capture is unavailable.

    ``app`` (optional Flask app) is used to give the DB-touching flush
    thread an application context.
    """
    from netshield.services.network_scanner import packet_capability_available
    if not packet_capability_available():
        return False
    with _stats_lock:
        _stats["started_at"] = utcnow().isoformat()
    thread = threading.Thread(target=_sniff_loop, args=(app,), daemon=True,
                              name="dns-sniffer")
    thread.start()
    _flush_thread = threading.Thread(target=_flush_loop, args=(app,),
                                     daemon=True, name="dns-flush")
    _flush_thread.start()
    return True


def _flush_loop(app=None) -> None:
    while True:
        time.sleep(FLUSH_INTERVAL)
        try:
            if app is not None:
                with app.app_context():
                    _flush()
            else:
                _flush()
        except Exception as exc:
            logger.warning("flush loop error: %s", exc)



def noise_exclude_filter():
    """SQL filter that excludes noise rows at QUERY time — a bulletproof
    guarantee that reverse-DNS lookups and connectivity checks never appear
    in the UI, even if old rows still exist in the database."""
    import sqlalchemy as sa
    patterns = [f"%{s}" for s in NOISE_SUFFIXES]
    patterns += [f"%{d}" for d in NOISE_DOMAINS if "." in d]
    return ~sa.or_(*[DnsQueryLog.domain.like(p) for p in patterns])


def top_domains(days: int, device_mac: str | None = None,
                limit: int = 20) -> list[dict]:
    """Top domains by query count over the last N days (network-wide or
    filtered to one device) — built from the hourly-bucketed table."""
    cutoff = utcnow() - timedelta(days=days)
    q = (db.session.query(DnsQueryLog.domain,
                          db.func.sum(DnsQueryLog.count).label("total"))
         .filter(DnsQueryLog.timestamp >= cutoff, noise_exclude_filter()))
    if device_mac:
        q = q.filter(DnsQueryLog.device_mac == device_mac)
    rows = (q.group_by(DnsQueryLog.domain)
            .order_by(db.desc("total")).limit(limit).all())
    from netshield.services.dns_categories import classify
    return [{"domain": d, "count": int(n), "categories": classify(d)}
            for d, n in rows]


def history_rows(page: int = 1, per_page: int = 25, q: str | None = None,
                 device_mac: str | None = None):
    """Searchable/filterable/paginated history: domain, device, first seen,
    last seen, count (one row per device+domain)."""
    query = (db.session.query(
        DnsQueryLog.device_mac,
        DnsQueryLog.domain,
        db.func.min(DnsQueryLog.timestamp).label("first_seen"),
        db.func.max(DnsQueryLog.timestamp).label("last_seen"),
        db.func.sum(DnsQueryLog.count).label("total"),
    ).group_by(DnsQueryLog.device_mac, DnsQueryLog.domain)
     .filter(noise_exclude_filter()))
    if q:
        query = query.filter(DnsQueryLog.domain.like(f"%{q.strip().lower()}%"))
    if device_mac:
        query = query.filter(DnsQueryLog.device_mac == device_mac)
    query = query.order_by(db.desc("last_seen"))
    return query.paginate(page=page, per_page=per_page, error_out=False)


def history_export_rows(q: str | None = None, device_mac: str | None = None):
    """All matching rows (no pagination) for CSV export."""
    query = (db.session.query(
        DnsQueryLog.device_mac,
        DnsQueryLog.domain,
        db.func.min(DnsQueryLog.timestamp).label("first_seen"),
        db.func.max(DnsQueryLog.timestamp).label("last_seen"),
        db.func.sum(DnsQueryLog.count).label("total"),
    ).group_by(DnsQueryLog.device_mac, DnsQueryLog.domain)
     .filter(noise_exclude_filter()))
    if q:
        query = query.filter(DnsQueryLog.domain.like(f"%{q.strip().lower()}%"))
    if device_mac:
        query = query.filter(DnsQueryLog.device_mac == device_mac)
    return (query.order_by(db.desc("last_seen")).all())


def purge(retention_days: int) -> dict:
    """Delete query-log + bandwidth rows older than the retention period."""
    cutoff = utcnow() - timedelta(days=max(retention_days, 1))
    n_dns = DnsQueryLog.query.filter(DnsQueryLog.timestamp < cutoff).delete()
    n_bw = BandwidthSample.query.filter(BandwidthSample.timestamp < cutoff).delete()
    db.session.commit()
    return {"dns_rows": n_dns, "bandwidth_rows": n_bw}


# The scope-limitation note rendered in the UI (search terms / page content
# are inside encrypted HTTPS and are NOT visible at the DNS layer).
SCOPE_NOTE = (
    "DNS-level visibility only: this console shows which domains devices "
    "queried. It does not show search-engine terms, usernames, or the "
    "specific pages/content viewed — those travel inside encrypted HTTPS "
    "and are out of scope. Nothing here is inferred; only DNS-layer "
    "observations are displayed."
)
